### ISSUE TITLE
support parallelization

### ISSUE THREAD

**Issue by akhmerov** [jupyter-widgets/jupyter-sphinx#30]
Sphinx has a [limited support for parallelization](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-j).

Because code execution via jupyter is likely a bottleneck, it's worth double-checking that this part is indeed parallelizable.

**Comment by jbweston** [comment]
seems just passing `SPHINXOPTS="-j8"` does not do anything for our extension.

**Comment by akhmerov** [comment]
Right, I expect we would need to investigate that much closer, and this is probably a tough issue.
