### ISSUE TITLE
Verify that nothing breaks downstream

### ISSUE THREAD

**Issue by akhmerov** [jupyter-widgets/jupyter-sphinx#33]
There are several project relying on the old machinery. It is however superseded by the new implementation. We should decide how to deal with that and communicate with maintainers of other libraries.

**Comment by akhmerov** [comment]
I've looked through github to see repos using the old jupyter-sphinx, here's what I found:

* https://github.com/jupyter-widgets/ipywidgets
* https://github.com/QuantStack/ipysheet
* https://github.com/maartenbreddels/ipyvolume
* https://github.com/pymc-learn/pymc-learn
* https://github.com/maartenbreddels/ipywebrtc
* https://github.com/vaexio/vaex
* https://github.com/nipy/niwidgets
* https://github.com/refnx/refnx
* https://github.com/MaayanLab/clustergrammer-docs
* https://github.com/sdpython/papierstat

There are many more hits on "jupyter-sphinx" search, but I believe all of the rest are noise (bots, mentions without using the library, or students of applied data science with Python, where jupyter-sphinx was recommended as a tool).

**Comment by akhmerov** [comment]
My proposal:

- Do all the other issues in the milestone, including removal of the old implementation.
- Make and publish an rc
- Open an issue in all the downstream repositories alerting the maintainers of the upcoming change and suggesting possible strategies for dealing with the update (pin the version/rewrite the docs).
- Wait about a week, flip the switch.

Pinging @SylvainCorlay @jbweston @maartenbreddels

**Comment by vidartf** [comment]
I don't know how you generated that list of projects, but it is not exhaustive. I maintain at least a handful of other projects that rely on this as well (thanks!). One example is pythreejs. Or am I missing something in what you mean by "relying on it"? I've noticed a bunch of work being done here, but have not had the time to look closely enough at it to figure out exactly what is changing.

**Comment by akhmerov** [comment]
@vidartf thanks for checking in! I've generated this list of projects by searching for "jupyter-sphinx" on github and selecting the hits that were actually using it. pythreejs repository doesn't have jupyter-sphinx mentioned in the codebase and that's why I didn't find it; how do you use jupyter-sphinx there (asking to refine the search criteria)?

**Comment by akhmerov** [comment]
Also about the work being done here: this repo will now be able to work with any jupyter code and output and not just, not just widgets.

**Comment by vidartf** [comment]
> . pythreejs repository doesn't have jupyter-sphinx mentioned in the codebase

I'm not sure how the github search works, but jupyter-sphinx is defininty mentioned in the codebase. Some examples:
- https://github.com/jupyter-widgets/pythreejs/blob/462efa8f8225fdad885f13102c49e57aa9f63ab7/setup.py#L89
- https://github.com/jupyter-widgets/pythreejs/blob/462efa8f8225fdad885f13102c49e57aa9f63ab7/docs/source/conf.py#L34

**Comment by akhmerov** [comment]
I'll double-check what goes wrong and extend the list.

**Comment by SylvainCorlay** [comment]
> My proposal:
>
> - Do all the other issues in the milestone, including removal of the old implementation.
> - Make and publish an rc
> - Open an issue in all the downstream repositories alerting the maintainers of the upcoming change and suggesting possible strategies for dealing with the update (pin the version/rewrite the docs).
> - Wait about a week, flip the switch.
>

That sounds like a good plan. Opening issues downstream with a standard text that we would reuse everywhere sounds reasonable as well.

I think that 0.2rc could be announced in a blog post, which another way of informing downstream.

**Comment by akhmerov** [comment]
@SylvainCorlay v0.2.0rc1 is tagged, can you please release it on pypi?

A blog post is a great idea, how to go about it?

**Comment by SylvainCorlay** [comment]
@akhmerov this is great news!

For the blog post, the [Jupyter blog](https://blog.jupyter.org) uses medium. If you have an account, I can add you as a "writer" for the blog so that you can submit a draft.

If you don't yet have an account, you can create one from your twitter account, which is a good way to have people mention you. Just let me know your medium handle.

**Comment by akhmerov** [comment]
Thanks. My medium account is `anton.akhmerov`.

**Comment by SylvainCorlay** [comment]
@akhmerov I just added you as a writer.

**Comment by akhmerov** [comment]
- [x] other issues in the milestone
- [x] 0.2.0rc1
- [x] Blog post
- [x] https://github.com/jupyter-widgets/ipywidgets/pull/2424

**Comment by akhmerov** [comment]
@SylvainCorlay if you're OK with it, I will post a standard message to the libs using the jupyter-sphinx as well as a different one that have used it in the past, but still list it in the `conf.py` (because those might be interested in the update as well).

**Comment by akhmerov** [comment]
I've opened the issues everywhere I could find, and updated the ipywidgets docs.

**Comment by akhmerov** [comment]
I've opened the downstream issues.

**Comment by akhmerov** [comment]
Closing because everyone had enough time to react—a month should mean that nobody is blindsided.
