### ISSUE TITLE
Setup tests and CI

### ISSUE THREAD

**Issue by akhmerov** [jupyter-widgets/jupyter-sphinx#37]

**Comment by jbweston** [comment]
What should the tests look like, actually?

I could imagine running sphinx against a bunch of documents and checking that it at least completes successfully, but I'm not sure what comprehensive tests would look like. Maybe some python script using beautiful soup?

**Comment by akhmerov** [comment]
I think rather checking that the parse tree has nodes with proper types.

**Comment by jbweston** [comment]
I'm not sure how we can get access to this information: does sphinx provided the necessary APIs to be able to say "process this one document"? I've only ever seen `sphinx.main()`

**Comment by akhmerov** [comment]
Tests were implemented in #42, CI remaining.
