### ISSUE TITLE
support thebelab out of the box

### ISSUE THREAD

**Issue by akhmerov** [jupyter-widgets/jupyter-sphinx#41]
This is more work than just flicking a switch: we need to change the behavior of hidden code from not being shown to being in DOM but invisible until thebelab is activated.

**Comment by hugokerstens** [comment]
I will start working on this. We will use the predefined output functionality of thebelab for showing the output on initial page load.

How do we want thebelab to show on the page for end users? I suggest the following:
- No differences on initial page load, but add a button at the top (only when there are thebelab enables cells)
- This button transforms all outputs to a thebelab cell, with the original content as predefined output.

How do we want the developer to enable thebelab? Possible options:
- Global toggle option for all cells
- A specific cell type/option to enable it for a cell (opt-in)
- On by default, specific cell type/options to disable it for a certain cell (opt-out)

**Comment by akhmerov** [comment]
> This button transforms all ~~outputs~~ inputs to a thebelab cell, with the original content as predefined output.

Yes, also clicking on this button shows the inputs that were previously not shown.

> How do we want the developer to enable thebelab?

I think if the developer provides a global thebelab configuration, it should become available everywhere.
