### ISSUE TITLE
handle stderr

### ISSUE THREAD

**Issue by akhmerov** [jupyter-widgets/jupyter-sphinx#48]
Right now we are including `stdout` but ignoring stderr ([relevant lines](https://github.com/jupyter-widgets/jupyter-sphinx/blob/master/jupyter_sphinx/execute.py#L380-L387)).

We should also handle stderr on a similar footing, but not immediately sure what's the optimal approach.

**Comment by SylvainCorlay** [comment]
Maybe just style it differently and/or enable it with an option.
