### ISSUE TITLE
WARNING: download file not readable using jupyter-download

### ISSUE THREAD

**Issue by berceanu** [jupyter-widgets/jupyter-sphinx#55]
When using `:jupyter-download:script:` or `:jupyter-download:notebook:` in my
[usage.rst](https://raw.githubusercontent.com/berceanu/sliceplots/master/docs/usage.rst) and building my project's docs locally via 

```
~/Development/sliceplots/docs/usage.rst:87: WARNING: download file not readable: ~/Development/sliceplots/docs/_build/jupyter_execute/somename.py
~/Development/sliceplots/docs/usage.rst:87: WARNING: download file not readable: ~/Development/sliceplots/docs/_build/jupyter_execute/somename.ipynb
```

However, the `docs/_build/jupyter_execute` does contain `usage.ipynb` and `usage.py`, so if I change `:jupyter-download:script:`somename`` to `:jupyter-download:script:`usage`` then sphinx finds the files. 

The same behaviour is also present on [RTD](https://sliceplots.readthedocs.io/en/latest/usage.html).

**Comment by akhmerov** [comment]
The name of the document you download must coincide with the id you provide to the kernel. It's described [here](https://jupyter-sphinx.readthedocs.io/en/latest/#downloading-the-code-as-a-script), although perhaps not in the most clear way.

Can you verify whether providing the jupyter kernel id works for you?

**Comment by berceanu** [comment]
But I did not specify the kernel `id` anywhere.

**Comment by akhmerov** [comment]
Right, so before the beginning of the code you should include

```rst
.. jupyter-kernel::
  :id: filename
```

**Comment by berceanu** [comment]
Solved, thank you!

**Comment by jbweston** [comment]
Seems like this is solved.
