### ISSUE TITLE
work with 3rd party package yet (e.g: nglview)?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/jupyter-sphinx#6]
thanks for this cool project.

I've tried with [nglview](https://github.com/arose/nglview) but got 
```bash
Code Execution failed:AttributeError: 'NoneType' object has no attribute 'session'
  e.__class__.__name__, str(e)))
```

Works fine with `ipywidgets.Text`
![capture](https://cloud.githubusercontent.com/assets/4451957/21782039/f0bfccee-d67f-11e6-8f85-65c26ed094af.png)

**Comment by hainm** [comment]
this is the expected output if using `nglview`

![nglview](https://cloud.githubusercontent.com/assets/4451957/21782070/0f0cea74-d680-11e6-9bcd-2e755e0c3045.png)

**Comment by hainm** [comment]
cc @arose

**Comment by SylvainCorlay** [comment]
@hainm this requires ipywidgets 6.0 (recent beta or release candidate). It should work with custom widgets.

Closing this issue.
