### ISSUE TITLE
No module named 'jupyter_sphinx.execute

### ISSUE THREAD

**Issue by djangoliv** [jupyter-widgets/jupyter-sphinx#63]
I did not manage to run the extension with same conf.py as https://github.com/jupyter-widgets/jupyter-sphinx/blob/master/doc/source/conf.py.

```
>> make html
Running Sphinx v1.8.5
loading translations [fr]... fait

Extension error:
Could not import extension jupyter_sphinx.execute (exception: No module named 'jupyter_sphinx.execute')
Makefile:34 : la recette pour la cible « html » a échouée
make: *** [html] Erreur 2
```

Environment:
Python 3.5.3
nbconvert 5.5.0
sphinx 1.8.5
ipywidgets 7.5.0

Regards

**Comment by SylvainCorlay** [comment]
is `jupyter_sphinx` installed?

**Comment by akhmerov** [comment]
@djangoliv more specifically, did you run `pip install --pre jupyter-sphinx` in the environment where you're building the docs?

**Comment by djangoliv** [comment]
Yes I did:

>>> import jupyter_sphinx
>>> jupyter_sphinx.__version__
'0.1.4'

**Comment by akhmerov** [comment]
It looks like you've missed the `--pre` flag, you need the version `0.2.0rc1`. We're also releasing `0.2.0` real soon™ (hopefully later today).

**Comment by djangoliv** [comment]
Ho ok, thanks. I had to do 
 `pip install --pre jupyter-sphinx -U`

Thanks and regard

**Comment by akhmerov** [comment]
If you instead install from master (`pip install git+https://github.com/jupyter-widgets/jupyter-sphinx.git -U`), you can also give thebelab a test drive.

I'm closing the issue.
