### ISSUE TITLE
LICENSE not included in python package

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/jupyter-sphinx#8]
I see the package I downloaded from pypi does not include the license file.

**Comment by jakirkham** [comment]
Should be a simple matter of adding it to the `MANIFEST.in`.

**Comment by SylvainCorlay** [comment]
Now fixed.

**Comment by jakirkham** [comment]
xref: https://github.com/jupyter-widgets/jupyter-sphinx/commit/1db44a9d21aaba95e639cca006818ce218abbc6f
